CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  first_name VARCHAR(50),
  last_name VARCHAR(50)
);

CREATE TABLE sounds (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  title VARCHAR(50),
  path VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE tracks (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  sound_id INTEGER NOT NULL REFERENCES sounds(id),
  title VARCHAR(50),
  path VARCHAR(200) UNIQUE NOT NULL
);